In [1]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.4.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-2.4.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.4.0


In [2]:
!pip install tensorflow==1.15 # 1.15 버전 Tensorflow 설치

     |████████████████████████████████| 412.3MB 37kB/s 
     |████████████████████████████████| 51kB 6.9MB/s 
     |████████████████████████████████| 512kB 48.0MB/s 
     |████████████████████████████████| 3.8MB 44.7MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=532960b6b79f500ce1d5591358bbe94a0de43ae44fe8283609e19d7709a4c97c
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorboard 2.4.0
    Uninstalling tensorboard-2.4.0:
      Successfully uninstalled tensorboard-2.4.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully 

# Multivariable linear regression

In [3]:
import tensorflow as tf
tf.set_random_seed(777)

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [4]:
# cost/lost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y:y_data})
    if step % 200 == 0: print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)

0 Cost :  62547.29 
Prediction : 
 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]
200 Cost :  12.5621395 
Prediction : 
 [146.20279 188.21931 179.0293  195.4085  146.1889 ]
400 Cost :  11.298648 
Prediction : 
 [146.46979 188.03654 179.11147 195.46513 145.95143]
600 Cost :  10.164865 
Prediction : 
 [146.72278 187.86342 179.18935 195.51869 145.72656]
800 Cost :  9.147448 
Prediction : 
 [146.96248 187.69937 179.26315 195.5693  145.51363]
1000 Cost :  8.234464 
Prediction : 
 [147.1896  187.54395 179.33308 195.61716 145.31201]
1200 Cost :  7.415207 
Prediction : 
 [147.4048  187.39668 179.39937 195.66235 145.12111]
1400 Cost :  6.680026 
Prediction : 
 [147.6087  187.25717 179.46219 195.70505 144.94034]
1600 Cost :  6.020313 
Prediction : 
 [147.80191 187.125   179.52174 195.74542 144.7692 ]
1800 Cost :  5.4283013 
Prediction : 
 [147.98499 186.99977 179.57819 195.78354 144.60716]
2000 Cost :  4.897013 
Prediction : 
 [148.15846 186.88112 179.63167 195.81955 144.45374]
2200 Co

# Multivariable linear regerssion using matrix

In [6]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape = [None, 3]) # the shape of X is (n, 3)
Y = tf.placeholder(tf.float32, shape = [None, 1]) # the shape of Y is (n. 1)

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = "bias")

hypothesis = tf.matmul(X, W) + b

In [7]:
# cost/lost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [8]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y:y_data})
    if step % 100 == 0: print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)

0 Cost :  126121.6 
Prediction : 
 [[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]
100 Cost :  12.159109 
Prediction : 
 [[155.73917]
 [181.59718]
 [181.78825]
 [198.3048 ]
 [136.83037]]
200 Cost :  11.551899 
Prediction : 
 [[155.61072]
 [181.68556]
 [181.74934]
 [198.27315]
 [136.94933]]
300 Cost :  10.976598 
Prediction : 
 [[155.48576]
 [181.77159]
 [181.7115 ]
 [198.2423 ]
 [137.06516]]
400 Cost :  10.431516 
Prediction : 
 [[155.36418]
 [181.8553 ]
 [181.6747 ]
 [198.21219]
 [137.17793]]
500 Cost :  9.915052 
Prediction : 
 [[155.24588]
 [181.93675]
 [181.6389 ]
 [198.18283]
 [137.28775]]
600 Cost :  9.425737 
Prediction : 
 [[155.13078]
 [182.01599]
 [181.60406]
 [198.15417]
 [137.39467]]
700 Cost :  8.9621105 
Prediction : 
 [[155.01881]
 [182.09311]
 [181.57019]
 [198.12622]
 [137.49878]]
800 Cost :  8.522844 
Prediction : 
 [[154.90987]
 [182.16814]
 [181.53726]
 [198.09897]
 [137.60016]]
900 Cost :  8.1065855 
Prediction : 
 [[154.80386]
 [182.24115]
 

# Multivariable linear regerssion using file data

In [9]:
import tensorflow as tf
import numpy as np
import pandas as pd
from google.colab import drive, files
tf.set_random_seed(777)

In [10]:
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
xy = np.loadtxt('/content/drive/My Drive/모두의 딥러닝/data_01_test_score.csv', delimiter=',', dtype = np.float32)

In [12]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data, "\nx_data shape : ", x_data.shape)
print(y_data, "\ny_data shape : ", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape :  (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape :  (25, 1)


In [13]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

# cost/lost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _  = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 1000 == 0 : print(step, "Cost : ", cost_val, "\nPrediction\n", hy_val)

0 Cost :  20682.217 
Prediction
 [[15.3530855]
 [25.620491 ]
 [21.435873 ]
 [23.021599 ]
 [21.901628 ]
 [17.103834 ]
 [15.216542 ]
 [ 8.105922 ]
 [25.533789 ]
 [23.99665  ]
 [17.138174 ]
 [20.137476 ]
 [22.434807 ]
 [19.68472  ]
 [16.372953 ]
 [25.100708 ]
 [21.371382 ]
 [16.114529 ]
 [20.338524 ]
 [17.508432 ]
 [18.731852 ]
 [23.45593  ]
 [17.350943 ]
 [16.195797 ]
 [25.42364  ]]
1000 Cost :  16.523172 
Prediction
 [[150.9708 ]
 [187.28824]
 [181.3857 ]
 [197.59253]
 [144.56012]
 [107.95556]
 [146.81857]
 [107.00665]
 [176.77118]
 [164.78589]
 [143.14893]
 [143.94211]
 [187.27704]
 [156.0903 ]
 [148.42224]
 [189.63522]
 [150.41171]
 [174.59534]
 [177.63765]
 [158.4658 ]
 [172.73198]
 [175.57275]
 [164.18411]
 [151.99405]
 [193.0055 ]]
2000 Cost :  12.499547 
Prediction
 [[151.37332]
 [186.6808 ]
 [181.32706]
 [197.80377]
 [143.59833]
 [107.54326]
 [147.69214]
 [108.68681]
 [176.28647]
 [164.8475 ]
 [143.38248]
 [143.79631]
 [186.91386]
 [155.31927]
 [149.16728]
 [189.38242]
 [149.0038

In [15]:
print('Your score will be ', sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print('Other score will be ', sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90,100,80]]}))

Your score will be  [[194.89839]]
Other score will be  [[165.0794 ]
 [176.52182]]


# Multivariable linear regerssion using Queue runners

In [29]:
import tensorflow as tf
from google.colab import drive, files
drive.mount('/content/drive')
tf.set_random_seed(777)

filename_queue = tf.train.string_input_producer(
    ['/content/drive/My Drive/모두의 딥러닝/data_01_test_score.csv'], shuffle = False, name = 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [30]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [31]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [32]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y:y_batch})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
    
coord.request_stop()
coord.join(threads)

In [ ]:
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))